# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_name', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=10)),
                ('caste', models.CharField(max_length=40)),
                ('religion', models.CharField(max_length=40)),
                ('birth_village', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('father_occupation', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=10)),
            ],
        ),
    ]
